#!/bin/sh
# Tests del hook arranque.sh.
#
# Por que existen: un hook de arranque que revienta deja la sesion sin contexto,
# y uno que avisa de lo que no toca se aprende a ignorar. Lo que se protege aqui
# es sobre todo el aviso de guardas SIN ACTIVAR: es el mecanismo que impide que
# "acuerdate de activarla" se quede pendiente para siempre. Tiene que aparecer
# cuando hay decision pendiente, DESAPARECER cuando se toma, y no romper nunca
# el arranque.
#
# Uso: sh test_arranque.sh     (exit 1 si algun caso falla)
set -u
AQUI="$(cd "$(dirname "$0")" && pwd)"
HOOK="$AQUI/arranque.sh"
TMP="${TMPDIR:-/tmp}/test-arranque.$$"
FALLIDOS=0

limpiar() { rm -rf "$TMP"; mkdir -p "$TMP/.github/workflows"; }
trap 'rm -rf "$TMP"' EXIT

comprobar() { # comprobar <nombre> <condicion-ya-evaluada:0|1>
    if [ "$2" -eq 0 ]; then
        printf '  ok    %s\n' "$1"
    else
        printf '  FALLO %s\n' "$1"
        FALLIDOS=$((FALLIDOS + 1))
    fi
}

correr() { (cd "$TMP" && sh "$HOOK" 2>&1); }

echo "Tests de arranque.sh"

# --- Sin guardas desactivadas: ni una palabra del tema -----------------------
limpiar
: > "$TMP/.github/workflows/ci.yml"
SALIDA="$(correr)"; CODIGO=$?
comprobar "proyecto sin guardas pendientes: no menciona el tema" \
    "$(printf '%s' "$SALIDA" | grep -qi 'SIN ACTIVAR' && echo 1 || echo 0)"
comprobar "y aun asi inyecta el contexto de protocolo" \
    "$(printf '%s' "$SALIDA" | grep -q '/que-toca' && echo 0 || echo 1)"
comprobar "exit 0 (un hook nunca rompe el arranque)" "$CODIGO"

# --- Con una guarda desactivada: avisa Y da el comando exacto ----------------
limpiar
: > "$TMP/.github/workflows/audit.yml.desactivado"
SALIDA="$(correr)"; CODIGO=$?
comprobar "guarda desactivada: AVISA" \
    "$(printf '%s' "$SALIDA" | grep -qi 'SIN ACTIVAR' && echo 0 || echo 1)"
comprobar "dice el comando exacto para activarla" \
    "$(printf '%s' "$SALIDA" | grep -q 'git mv .github/workflows/audit.yml.desactivado .github/workflows/audit.yml' && echo 0 || echo 1)"
comprobar "explica el prerrequisito de esa guarda (GESTOR)" \
    "$(printf '%s' "$SALIDA" | grep -q 'GESTOR' && echo 0 || echo 1)"
comprobar "ofrece la salida de borrarla (no decidir tambien es un estado)" \
    "$(printf '%s' "$SALIDA" | grep -q 'sin tomar' && echo 0 || echo 1)"
comprobar "exit 0" "$CODIGO"

# --- Varias a la vez: las nombra todas ---------------------------------------
limpiar
: > "$TMP/.github/workflows/audit.yml.desactivado"
: > "$TMP/.github/workflows/proteccion-main.yml.desactivado"
SALIDA="$(correr)"
comprobar "dos guardas pendientes: nombra las dos" \
    "$(printf '%s' "$SALIDA" | grep -q 'audit.yml' && printf '%s' "$SALIDA" | grep -q 'proteccion-main.yml' && echo 0 || echo 1)"
comprobar "cada una con su prerrequisito propio (rulesets)" \
    "$(printf '%s' "$SALIDA" | grep -q 'rulesets' && echo 0 || echo 1)"

# --- Al ACTIVARLA, el aviso desaparece solo ----------------------------------
limpiar
: > "$TMP/.github/workflows/audit.yml"
SALIDA="$(correr)"
comprobar "TRAS ACTIVARLA: el aviso desaparece (no se vuelve ruido de fondo)" \
    "$(printf '%s' "$SALIDA" | grep -qi 'SIN ACTIVAR' && echo 1 || echo 0)"

# --- Guarda desconocida: se nombra igual, sin inventarse instrucciones -------
limpiar
: > "$TMP/.github/workflows/lo-que-sea.yml.desactivado"
SALIDA="$(correr)"
comprobar "workflow desconocido: lo nombra sin inventar prerrequisitos" \
    "$(printf '%s' "$SALIDA" | grep -q 'lo-que-sea.yml' && echo 0 || echo 1)"

# --- Hook pre-push declarado pero NO instalado: avisa -------------------------
# Es el caso que motiva el aviso: .git/hooks no viaja con git pull, asi que un
# clon anterior al hook se queda sin la guarda y nada se lo dice.
limpiar
printf 'repos:\n  - repo: local\n    hooks:\n      - id: ci-local\n        stages: [pre-push]\n' > "$TMP/.pre-commit-config.yaml"
mkdir -p "$TMP/.git/hooks"
SALIDA="$(correr)"; CODIGO=$?
comprobar "pre-push declarado y NO instalado: AVISA" \
    "$(printf '%s' "$SALIDA" | grep -qi 'falta el hook pre-push' && echo 0 || echo 1)"
comprobar "dice el comando exacto para instalarlo" \
    "$(printf '%s' "$SALIDA" | grep -q 'pre-commit install' && echo 0 || echo 1)"
comprobar "exit 0 (avisar no es romper el arranque)" "$CODIGO"

# --- Ya instalado: silencio (si no, se vuelve ruido de fondo) ----------------
# OJO al `printf`: al principio este caso creaba el fichero VACIO (`: >`) y daba por
# instalado el hook. Eso era el agujero 2 — un fichero vacio no es una guarda—,
# asi que ahora se escribe el marcador real que pre-commit pone en su cabecera.
# El caso de abajo cubre lo contrario.
instalar_hook() { # instalar_hook <tipo> — replica lo que escribe `pre-commit install`
    printf '#!/usr/bin/env bash\n# File generated by pre-commit: https://pre-commit.com\nexit 0\n' \
        > "$TMP/.git/hooks/$1"
}
limpiar
printf 'repos:\n  - repo: local\n    hooks:\n      - id: ci-local\n        stages: [pre-push]\n' > "$TMP/.pre-commit-config.yaml"
mkdir -p "$TMP/.git/hooks"; instalar_hook pre-push; instalar_hook pre-commit
SALIDA="$(correr)"
comprobar "TRAS INSTALARLO: el aviso desaparece solo" \
    "$(printf '%s' "$SALIDA" | grep -qi 'falta el hook' && echo 1 || echo 0)"

# --- Agujero 1: falta OTRO tipo distinto de pre-push ------------------
# El caso real: el clon se instalo cuando el repo declaraba un solo tipo. Antes
# antes esto pasaba callado porque solo se miraba pre-push.
limpiar
printf 'default_install_hook_types: [pre-commit, pre-push]\nrepos:\n  - repo: local\n    hooks:\n      - id: algo\n' > "$TMP/.pre-commit-config.yaml"
mkdir -p "$TMP/.git/hooks"; instalar_hook pre-push
SALIDA="$(correr)"
comprobar "falta SOLO pre-commit: AVISA (antes callaba)" \
    "$(printf '%s' "$SALIDA" | grep -qi 'falta el hook pre-commit' && echo 0 || echo 1)"
comprobar "y NO se queja del que si esta instalado" \
    "$(printf '%s' "$SALIDA" | grep -qi 'falta el hook pre-push' && echo 1 || echo 0)"

# --- Agujero 2: el fichero existe pero no lo genero pre-commit --------
# Un hook heredado de otro flujo o escrito a mano. Antes bastaba con que
# existiera, asi que daba verde teniendo CERO guarda: el peor de los dos casos,
# porque el dev que lo mira con `ls` se queda tranquilo.
limpiar
printf 'repos:\n  - repo: local\n    hooks:\n      - id: ci-local\n        stages: [pre-push]\n' > "$TMP/.pre-commit-config.yaml"
mkdir -p "$TMP/.git/hooks"; instalar_hook pre-commit
printf '#!/bin/sh\n# hook heredado de otro flujo\nexit 0\n' > "$TMP/.git/hooks/pre-push"
SALIDA="$(correr)"
comprobar "hook ajeno en su sitio: AVISA (antes daba falso verde)" \
    "$(printf '%s' "$SALIDA" | grep -qi 'falta el hook pre-push' && echo 0 || echo 1)"

# --- `stages` con valores que NO son hooks de git: no se inventa un aviso ----
limpiar
printf 'repos:\n  - repo: local\n    hooks:\n      - id: algo\n        stages: [manual]\n' > "$TMP/.pre-commit-config.yaml"
mkdir -p "$TMP/.git/hooks"; instalar_hook pre-commit
SALIDA="$(correr)"
comprobar "stage 'manual' no es un hook de git: NO avisa de el" \
    "$(printf '%s' "$SALIDA" | grep -qi 'falta el hook manual' && echo 1 || echo 0)"

# --- Config sin stage pre-push: no se inventa un aviso DE PRE-PUSH -----------
# Ojo al nombre, que antes decia "NO avisa de nada" y si avisaba: sin
# `default_install_hook_types` pre-commit instala el tipo `pre-commit`, no esta,
# y quejarse es lo CORRECTO. Lo que se comprueba es que no se invente uno de
# pre-push. Un test cuyo titulo afirma mas que su aserto es justo el patron que
# un proyecto real ya se ha comido tres veces.
limpiar
printf 'repos:\n  - repo: local\n    hooks:\n      - id: algo\n' > "$TMP/.pre-commit-config.yaml"
mkdir -p "$TMP/.git/hooks"
SALIDA="$(correr)"
comprobar "sin stage pre-push declarado: NO se inventa un aviso de pre-push" \
    "$(printf '%s' "$SALIDA" | grep -qi 'falta el hook pre-push' && echo 1 || echo 0)"
comprobar "...y SI avisa del pre-commit, que es el que instalaria por defecto" \
    "$(printf '%s' "$SALIDA" | grep -qi 'falta el hook pre-commit' && echo 0 || echo 1)"

# --- YAML de BLOQUE: no se puede parsear, y se DICE --------------------------
# La forma de bloque es YAML valido y la escribiria cualquier formateador. El
# sed solo entiende la de flujo: antes caia al defecto EN SILENCIO y el agujero
# 1 volvia sin que nadie lo notara. Aqui pre-commit esta instalado y
# pre-push NO, que es el caso real observado: sin el aviso nuevo, esta config
# pasaria en verde.
limpiar
printf 'default_install_hook_types:\n  - pre-commit\n  - pre-push\nrepos:\n  - repo: local\n    hooks:\n      - id: algo\n' \
    > "$TMP/.pre-commit-config.yaml"
mkdir -p "$TMP/.git/hooks"; instalar_hook pre-commit
SALIDA="$(correr)"
comprobar "config en BLOQUE: avisa de que no puede leer los tipos" \
    "$(printf '%s' "$SALIDA" | grep -qi 'no consigo leer' && echo 0 || echo 1)"
comprobar "...y nombra la clave que no supo leer, no un 'algo fallo'" \
    "$(printf '%s' "$SALIDA" | grep -qi 'default_install_hook_types' && echo 0 || echo 1)"
comprobar "...asi el caso de pre-push ausente NO pasa callado" \
    "$(printf '%s' "$SALIDA" | grep -qiE 'falta el hook|no consigo leer' && echo 0 || echo 1)"

# --- YAML MIXTO: una lista en flujo y otra en bloque -------------------------
# El caso que encontro una segunda review, y el mas facil de producir sin
# querer: los formateadores dejan las listas cortas en flujo y expanden las
# largas, o sea que escupen exactamente este fichero. Con la condicion de "no
# lei NADA", la primera lista llenaba `etapas`, el aviso no saltaba, y el
# pre-push de la segunda desaparecia sin rastro: el agujero 1 en version estrecha.
# Aqui pre-commit esta instalado y pre-push NO.
limpiar
printf 'repos:\n  - repo: local\n    hooks:\n      - id: uno\n        stages: [pre-commit]\n      - id: dos\n        stages:\n          - pre-push\n' \
    > "$TMP/.pre-commit-config.yaml"
mkdir -p "$TMP/.git/hooks"; instalar_hook pre-commit
SALIDA="$(correr)"
comprobar "config MIXTA: avisa aunque una de las listas si se leyera" \
    "$(printf '%s' "$SALIDA" | grep -qi 'no consigo leer' && echo 0 || echo 1)"
comprobar "...y nombra 'stages', que es la clave que quedo a medias" \
    "$(printf '%s' "$SALIDA" | grep -qi 'stages' && echo 0 || echo 1)"
comprobar "...asi el pre-push de la lista en bloque NO se pierde callado" \
    "$(printf '%s' "$SALIDA" | grep -qiE 'falta el hook|no consigo leer' && echo 0 || echo 1)"

# --- Flujo bien formado: el aviso nuevo NO aparece ----------------------------
# El contrapeso del caso de arriba: si se disparara con la config normal seria
# ruido en cada arranque, y un aviso que suena siempre no significa nada.
limpiar
printf 'default_install_hook_types: [pre-commit, pre-push]\nrepos:\n  - repo: local\n    hooks:\n      - id: algo\n        stages: [pre-push]\n' \
    > "$TMP/.pre-commit-config.yaml"
mkdir -p "$TMP/.git/hooks"; instalar_hook pre-commit; instalar_hook pre-push
SALIDA="$(correr)"
comprobar "config de flujo correcta: ni aviso de parseo ni de hooks" \
    "$(printf '%s' "$SALIDA" | grep -qiE 'no consigo leer|falta el hook' && echo 1 || echo 0)"

# --- `stages` comentado: no dispara el aviso de parseo -----------------------
# `.*stages:` cogia las lineas comentadas; anclado a principio de linea, ya no.
limpiar
printf 'default_install_hook_types: [pre-commit]\nrepos:\n  - repo: local\n    hooks:\n      - id: algo\n        # stages: [pre-push]\n' \
    > "$TMP/.pre-commit-config.yaml"
mkdir -p "$TMP/.git/hooks"; instalar_hook pre-commit
SALIDA="$(correr)"
comprobar "un 'stages:' COMENTADO no genera aviso fantasma" \
    "$(printf '%s' "$SALIDA" | grep -qiE 'no consigo leer|falta el hook' && echo 1 || echo 0)"

# --- Sin git y sin nada: sigue sin romperse ----------------------------------
rm -rf "$TMP"; mkdir -p "$TMP"
SALIDA="$(correr)"; CODIGO=$?
comprobar "directorio pelado (sin .github, sin progreso): exit 0" "$CODIGO"
comprobar "sin .pre-commit-config.yaml: tampoco avisa del pre-push" \
    "$(printf '%s' "$SALIDA" | grep -qi 'falta el hook pre-push' && echo 1 || echo 0)"

echo
if [ "$FALLIDOS" -eq 0 ]; then
    echo "Todos los casos OK."
else
    echo "$FALLIDOS caso(s) fallidos."
fi
[ "$FALLIDOS" -eq 0 ]
